service: cv2-numpy
provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: hello.world

custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: Dockerfile
    dockerExtraFiles:
      - /lib64/libgthread-2.0.so.0
      - /lib64/libglib-2.0.so.0
      - /lib64/libSM.so.6
      - /lib64/libICE.so.6
      - /lib64/libXrender.so.1
      - /lib64/libXext.so.6
      - /lib64/libX11.so.6
      - /lib64/libuuid.so.1
      - /lib64/libxcb.so.1
      - /lib64/libXau.so.6
      - /lib64/libGL.so.1
      - /lib64/libGLX.so.0
      - /lib64/libGLdispatch.so.0

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements
